### PR TITLE
Update data parsing, bypass fairlane protection

### PR DESCRIPTION
**Pull request by fbarbe00**
Purpose
=======
Pararius is now protected by "fairlane". To make this program work, the
user has to manually enter the cookies from their browser session.

### CODE REVIEW

**Comment by fbarbe00** [comment]
Hi @Isso , are there any plans to merge this?

**Comment by fbarbe00** [comment]
Hi @Isso , is this project still maintained?

**Comment by bart-jens** [comment]
Hi @fbarbe00, what Cookie values should be placed in the "COOKIES_FROM_BROWSER" field? Pararius seems to place multiple. Thanks!

**Comment by fbarbe00** [comment]
Hi @bart-jens , I tested it a while back and I now completely forgot... You can just copy all of them of course, and that should work.

**Comment by michaelt-of** [comment]
@fbarbe00 Thank you for your contribution.
I am wondering if this is still working? I have set the cookies but it seems not working

**Comment by fbarbe00** [comment]
I have just tested it again. The cookies successfully bypass the fairlane protection, but the html tags used in pararius have changed since. So I'm afraid that's it for now unless someone wants to find all the new tag names

**Comment by michaelt-of** [comment]
@fbarbe00 May I ask how to set the cookies? I got this error in the console

```
Scraping started
Scraping error
Error [ERR_FR_TOO_MANY_REDIRECTS]: Maximum number of redirects exceeded
    at RedirectableRequest._processResponse (/Users/.../Workplace/repository/pararius-apartment-hunting-dashboard/node_modules/follow-redirects/index.js:361:24)
    at ClientRequest.RedirectableRequest._onNativeResponse (/Users/.../Workplace/repository/pararius-apartment-hunting-dashboard/node_modules/follow-redirects/index.js:57:10)
    at Object.onceWrapper (node:events:646:26)
    at ClientRequest.emit (node:events:526:28)
    at HTTPParser.parserOnIncomingClient (node:_http_client:618:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
```

**Comment by fbarbe00** [comment]
Hi, I tried again today, and somehow this time it didn't work.
There were also a few mistakes on my branch, which I have fixed.
I would, however, recommend dropping this, unless someone is motivated to reverse engineer everything all over again (which I'm not)

**Pull request closed without merging**
